//context
import { AuthProvider } from "@/context/AuthContext";
import { GlobalProvider } from "@/context/GlobalContext";
import { TimeProvider } from "@/context/TimeTrackerContext";

import LayoutFeature from "@/features/Layout";
import Snackbar from "@/features/Snackbar";

//middleware
import ProtectRoute from "@/middleware/protectRoute";

import ThemeRegistry from "@/setting/ThemeRegistry/ThemeRegistry";

//fonts
import { inter, mulish } from "@/assets/fonts";

export const metadata = {
  title: "Admin Portal-My Girl Souz",
  description: "Generated by create next app",
};

//global
import "@/assets/styles/globals.css";
import "flowbite";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css"
          rel="stylesheet"
        />
      </head>

      <body className={`container-full ${inter.variable} ${mulish.variable}`}>

        <ThemeRegistry>
          <GlobalProvider>
            <Snackbar />
            <AuthProvider>
              <ProtectRoute>
                <TimeProvider>
                  <LayoutFeature>{children}</LayoutFeature>
                </TimeProvider>
              </ProtectRoute>
            </AuthProvider>
          </GlobalProvider>
        </ThemeRegistry>

        <script src="https://demo.tailadmin.com/bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/datepicker.min.js"></script>
      </body>
    </html>
  );
}
